/**
 * cg_model_1958_functions.c generated by SimulationX 4.2.1.68046 (12/15/20),
 * at 2023-08-17 5:21:42 PM
**/

#include "ITI_crt.h"
#include "cg_model_1958.h"
#include "cg_model_1958_functions.h"


/*Functions*/


/*Functions*/
ITI_real _der_environment_getVectorValue(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_real indexReal, ITI_real __der_environment_getVectorValue_indexReal_dot){
	ITI_real _partial_der__der_environment_getVectorValue_value__der_environment_getVectorValue_indexReal=0.;
	ITI_int first=0;
	ITI_real value=0.;
	ITI_int index=0;
	ITI_int last=0;
	ITI_real __der_environment_getVectorValue_value_dot=0.;
	/*stmts*/
	_partial_der__der_environment_getVectorValue_value__der_environment_getVectorValue_indexReal=0;
	if (__der_environment_getVectorValue_indexReal_dot!=0){
		first=1;
		last=12;
		index=(int)(__iti_real_min(__iti_int_max((int)floor(floor(indexReal)), first), last));
		value=u.intValues[ArrayIndex(u, "d", index-1)];
		_partial_der__der_environment_getVectorValue_value__der_environment_getVectorValue_indexReal=ArrayValInt(FillIntArray(Param_Mem,0, 1, __ARRAY_SIZE(u,1)),(ITI_int)(((ITI_int)(index)-1)));
	}
	__der_environment_getVectorValue_value_dot=_partial_der__der_environment_getVectorValue_value__der_environment_getVectorValue_indexReal*__der_environment_getVectorValue_indexReal_dot;
	return __der_environment_getVectorValue_value_dot;
}

ITI_real _der_environment_getAzimuth(Param_Declare_SimVar, Param_Declare_SimData, ITI_real actRealHour, ITI_real SolAlt, ITI_real lat, ITI_real delta, ITI_real __der_environment_getAzimuth_actRealHour_dot, ITI_real __der_environment_getAzimuth_SolAlt_dot, ITI_real __der_environment_getAzimuth_delta_dot){
	ITI_real __der_environment_getAzimuth_azimuth_dot=0.;
	ITI_real _partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_delta=0.;
	ITI_real _partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_SolAlt=0.;
	ITI_real _partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_actRealHour=0.;
	ITI_int sign=0;
	ITI_real azimuth=0.;
	/*stmts*/
	_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_delta=0;
	_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_SolAlt=0;
	_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_actRealHour=0;
	if (__der_environment_getAzimuth_actRealHour_dot!=0){
		sign=((actRealHour<=12) ? (-1) : (1));
		azimuth=3.1415926535897931+sign*acos(__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1));
		_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_actRealHour=0;
	}
	if (__der_environment_getAzimuth_SolAlt_dot!=0){
		sign=((actRealHour<=12) ? (-1) : (1));
		azimuth=3.1415926535897931+sign*acos(__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1));
		_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_SolAlt=sign*(((__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1)==1||__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1)==-1) ? (-100000000.) : (-(1/sqrt(1-__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1)*__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1))))))*(((__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1)>=1||(sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat))<-1) ? (0) : (((sin(SolAlt)*sin(SolAlt)*sin(lat)-sin(SolAlt)*sin(delta))*cos(lat))/(cos(SolAlt)*cos(lat)*cos(SolAlt)*cos(lat))+(cos(SolAlt)*sin(lat))/(cos(SolAlt)*cos(lat)))));
	}
	if (__der_environment_getAzimuth_delta_dot!=0){
		sign=((actRealHour<=12) ? (-1) : (1));
		azimuth=3.1415926535897931+sign*acos(__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1));
		_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_delta=sign*(((__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1)==1||__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1)==-1) ? (-100000000.) : (-(1/sqrt(1-__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1)*__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1))))))*(((__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1)>=1||(sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat))<-1) ? (0) : (-(cos(delta)/(cos(SolAlt)*cos(lat))))));
	}
	__der_environment_getAzimuth_azimuth_dot=_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_actRealHour*__der_environment_getAzimuth_actRealHour_dot+_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_SolAlt*__der_environment_getAzimuth_SolAlt_dot+_partial_der__der_environment_getAzimuth_azimuth__der_environment_getAzimuth_delta*__der_environment_getAzimuth_delta_dot;
	return __der_environment_getAzimuth_azimuth_dot;
}

ITI_real _der_building_grid_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U, ITI_real __der_building_grid_calc_current_P_dot, ITI_real __der_building_grid_calc_current_Q_dot){
	ITI_real __der_building_grid_calc_current_current_dot=0.;
	ITI_real _partial_der__der_building_grid_calc_current_S__der_building_grid_calc_current_Q=0.;
	ITI_real S=0.;
	ITI_real _partial_der__der_building_grid_calc_current_current__der_building_grid_calc_current_Q=0.;
	ITI_real current=0.;
	ITI_real _partial_der__der_building_grid_calc_current_S__der_building_grid_calc_current_P=0.;
	ITI_real _partial_der__der_building_grid_calc_current_current__der_building_grid_calc_current_P=0.;
	/*stmts*/
	_partial_der__der_building_grid_calc_current_current__der_building_grid_calc_current_Q=0;
	_partial_der__der_building_grid_calc_current_current__der_building_grid_calc_current_P=0;
	if (__der_building_grid_calc_current_P_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_grid_calc_current_S__der_building_grid_calc_current_P=((P*P+Q*Q==0) ? (((2*P==0) ? (0) : (100000000.))) : (P/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_grid_calc_current_current__der_building_grid_calc_current_P=((fabs(U)>1e-10) ? (_partial_der__der_building_grid_calc_current_S__der_building_grid_calc_current_P/U) : (0));
	}
	if (__der_building_grid_calc_current_Q_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_grid_calc_current_S__der_building_grid_calc_current_Q=((P*P+Q*Q==0) ? (((2*Q==0) ? (0) : (100000000.))) : (Q/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_grid_calc_current_current__der_building_grid_calc_current_Q=((fabs(U)>1e-10) ? (_partial_der__der_building_grid_calc_current_S__der_building_grid_calc_current_Q/U) : (0));
	}
	__der_building_grid_calc_current_current_dot=_partial_der__der_building_grid_calc_current_current__der_building_grid_calc_current_P*__der_building_grid_calc_current_P_dot+_partial_der__der_building_grid_calc_current_current__der_building_grid_calc_current_Q*__der_building_grid_calc_current_Q_dot;
	return __der_building_grid_calc_current_current_dot;
}

ITI_real _der_building_grid_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real __der_building_grid_calc_Phi_P_dot, ITI_real __der_building_grid_calc_Phi_Q_dot){
	ITI_real P_act=0.;
	ITI_real _partial_der__der_building_grid_calc_Phi_Phi__der_building_grid_calc_Phi_Q=0.;
	ITI_real _partial_der__der_building_grid_calc_Phi_Phi__der_building_grid_calc_Phi_P=0.;
	ITI_real _partial_der__der_building_grid_calc_Phi_P_act__der_building_grid_calc_Phi_P=0.;
	ITI_real Phi=0.;
	ITI_real __der_building_grid_calc_Phi_Phi_dot=0.;
	/*stmts*/
	_partial_der__der_building_grid_calc_Phi_Phi__der_building_grid_calc_Phi_Q=0;
	_partial_der__der_building_grid_calc_Phi_Phi__der_building_grid_calc_Phi_P=0;
	if (__der_building_grid_calc_Phi_P_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		_partial_der__der_building_grid_calc_Phi_P_act__der_building_grid_calc_Phi_P=((P>1e-10||P<-1e-10) ? (1) : (0));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_grid_calc_Phi_Phi__der_building_grid_calc_Phi_P=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (-((Q*_partial_der__der_building_grid_calc_Phi_P_act__der_building_grid_calc_Phi_P)/(P_act*P_act))*(((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))) : (0));
	}
	if (__der_building_grid_calc_Phi_Q_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_grid_calc_Phi_Phi__der_building_grid_calc_Phi_Q=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? ((((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))/P_act) : (0));
	}
	__der_building_grid_calc_Phi_Phi_dot=_partial_der__der_building_grid_calc_Phi_Phi__der_building_grid_calc_Phi_P*__der_building_grid_calc_Phi_P_dot+_partial_der__der_building_grid_calc_Phi_Phi__der_building_grid_calc_Phi_Q*__der_building_grid_calc_Phi_Q_dot;
	return __der_building_grid_calc_Phi_Phi_dot;
}

ITI_real _der_building_powerOutput1_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real __der_building_powerOutput1_calc_Phi_P_dot){
	ITI_real __der_building_powerOutput1_calc_Phi_Phi_dot=0.;
	ITI_real _partial_der__der_building_powerOutput1_calc_Phi_Phi__der_building_powerOutput1_calc_Phi_P=0.;
	ITI_real P_act=0.;
	ITI_real _partial_der__der_building_powerOutput1_calc_Phi_P_act__der_building_powerOutput1_calc_Phi_P=0.;
	ITI_real Phi=0.;
	/*stmts*/
	_partial_der__der_building_powerOutput1_calc_Phi_Phi__der_building_powerOutput1_calc_Phi_P=0;
	if (__der_building_powerOutput1_calc_Phi_P_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		_partial_der__der_building_powerOutput1_calc_Phi_P_act__der_building_powerOutput1_calc_Phi_P=((P>1e-10||P<-1e-10) ? (1) : (0));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_powerOutput1_calc_Phi_Phi__der_building_powerOutput1_calc_Phi_P=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (-((Q*_partial_der__der_building_powerOutput1_calc_Phi_P_act__der_building_powerOutput1_calc_Phi_P)/(P_act*P_act))*(((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))) : (0));
	}
	__der_building_powerOutput1_calc_Phi_Phi_dot=_partial_der__der_building_powerOutput1_calc_Phi_Phi__der_building_powerOutput1_calc_Phi_P*__der_building_powerOutput1_calc_Phi_P_dot;
	return __der_building_powerOutput1_calc_Phi_Phi_dot;
}

ITI_real _der_building_powerOutput1_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U, ITI_real __der_building_powerOutput1_calc_current_P_dot){
	ITI_real _partial_der__der_building_powerOutput1_calc_current_current__der_building_powerOutput1_calc_current_P=0.;
	ITI_real __der_building_powerOutput1_calc_current_current_dot=0.;
	ITI_real S=0.;
	ITI_real _partial_der__der_building_powerOutput1_calc_current_S__der_building_powerOutput1_calc_current_P=0.;
	ITI_real current=0.;
	/*stmts*/
	_partial_der__der_building_powerOutput1_calc_current_current__der_building_powerOutput1_calc_current_P=0;
	if (__der_building_powerOutput1_calc_current_P_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_powerOutput1_calc_current_S__der_building_powerOutput1_calc_current_P=((P*P+Q*Q==0) ? (((2*P==0) ? (0) : (100000000.))) : (P/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_powerOutput1_calc_current_current__der_building_powerOutput1_calc_current_P=((fabs(U)>1e-10) ? (_partial_der__der_building_powerOutput1_calc_current_S__der_building_powerOutput1_calc_current_P/U) : (0));
	}
	__der_building_powerOutput1_calc_current_current_dot=_partial_der__der_building_powerOutput1_calc_current_current__der_building_powerOutput1_calc_current_P*__der_building_powerOutput1_calc_current_P_dot;
	return __der_building_powerOutput1_calc_current_current_dot;
}

ITI_real _building_PelTable_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _der_building_cellar_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real __der_building_cellar_calc_Phi_P_dot, ITI_real __der_building_cellar_calc_Phi_Q_dot){
	ITI_real _partial_der__der_building_cellar_calc_Phi_Phi__der_building_cellar_calc_Phi_Q=0.;
	ITI_real Phi=0.;
	ITI_real _partial_der__der_building_cellar_calc_Phi_Phi__der_building_cellar_calc_Phi_P=0.;
	ITI_real P_act=0.;
	ITI_real _partial_der__der_building_cellar_calc_Phi_P_act__der_building_cellar_calc_Phi_P=0.;
	ITI_real __der_building_cellar_calc_Phi_Phi_dot=0.;
	/*stmts*/
	_partial_der__der_building_cellar_calc_Phi_Phi__der_building_cellar_calc_Phi_Q=0;
	_partial_der__der_building_cellar_calc_Phi_Phi__der_building_cellar_calc_Phi_P=0;
	if (__der_building_cellar_calc_Phi_P_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		_partial_der__der_building_cellar_calc_Phi_P_act__der_building_cellar_calc_Phi_P=((P>1e-10||P<-1e-10) ? (1) : (0));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_cellar_calc_Phi_Phi__der_building_cellar_calc_Phi_P=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (-((Q*_partial_der__der_building_cellar_calc_Phi_P_act__der_building_cellar_calc_Phi_P)/(P_act*P_act))*(((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))) : (0));
	}
	if (__der_building_cellar_calc_Phi_Q_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_cellar_calc_Phi_Phi__der_building_cellar_calc_Phi_Q=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? ((((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))/P_act) : (0));
	}
	__der_building_cellar_calc_Phi_Phi_dot=_partial_der__der_building_cellar_calc_Phi_Phi__der_building_cellar_calc_Phi_P*__der_building_cellar_calc_Phi_P_dot+_partial_der__der_building_cellar_calc_Phi_Phi__der_building_cellar_calc_Phi_Q*__der_building_cellar_calc_Phi_Q_dot;
	return __der_building_cellar_calc_Phi_Phi_dot;
}

ITI_real _der_building_cellar_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U, ITI_real __der_building_cellar_calc_current_P_dot, ITI_real __der_building_cellar_calc_current_Q_dot){
	ITI_real _partial_der__der_building_cellar_calc_current_current__der_building_cellar_calc_current_Q=0.;
	ITI_real _partial_der__der_building_cellar_calc_current_current__der_building_cellar_calc_current_P=0.;
	ITI_real __der_building_cellar_calc_current_current_dot=0.;
	ITI_real S=0.;
	ITI_real current=0.;
	ITI_real _partial_der__der_building_cellar_calc_current_S__der_building_cellar_calc_current_P=0.;
	ITI_real _partial_der__der_building_cellar_calc_current_S__der_building_cellar_calc_current_Q=0.;
	/*stmts*/
	_partial_der__der_building_cellar_calc_current_current__der_building_cellar_calc_current_Q=0;
	_partial_der__der_building_cellar_calc_current_current__der_building_cellar_calc_current_P=0;
	if (__der_building_cellar_calc_current_P_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_cellar_calc_current_S__der_building_cellar_calc_current_P=((P*P+Q*Q==0) ? (((2*P==0) ? (0) : (100000000.))) : (P/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_cellar_calc_current_current__der_building_cellar_calc_current_P=((fabs(U)>1e-10) ? (_partial_der__der_building_cellar_calc_current_S__der_building_cellar_calc_current_P/U) : (0));
	}
	if (__der_building_cellar_calc_current_Q_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_cellar_calc_current_S__der_building_cellar_calc_current_Q=((P*P+Q*Q==0) ? (((2*Q==0) ? (0) : (100000000.))) : (Q/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_cellar_calc_current_current__der_building_cellar_calc_current_Q=((fabs(U)>1e-10) ? (_partial_der__der_building_cellar_calc_current_S__der_building_cellar_calc_current_Q/U) : (0));
	}
	__der_building_cellar_calc_current_current_dot=_partial_der__der_building_cellar_calc_current_current__der_building_cellar_calc_current_P*__der_building_cellar_calc_current_P_dot+_partial_der__der_building_cellar_calc_current_current__der_building_cellar_calc_current_Q*__der_building_cellar_calc_current_Q_dot;
	return __der_building_cellar_calc_current_current_dot;
}

ITI_real _building_cellar_BaseLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_cellar_ElectricalPower_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_cellar_LightLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_cellar_MachineLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_cellar_NormLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_cellar_NumberPerson_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_cellar_ReactivePower_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _der_building_livingZone_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real __der_building_livingZone_calc_Phi_P_dot, ITI_real __der_building_livingZone_calc_Phi_Q_dot){
	ITI_real _partial_der__der_building_livingZone_calc_Phi_Phi__der_building_livingZone_calc_Phi_Q=0.;
	ITI_real __der_building_livingZone_calc_Phi_Phi_dot=0.;
	ITI_real _partial_der__der_building_livingZone_calc_Phi_Phi__der_building_livingZone_calc_Phi_P=0.;
	ITI_real P_act=0.;
	ITI_real _partial_der__der_building_livingZone_calc_Phi_P_act__der_building_livingZone_calc_Phi_P=0.;
	ITI_real Phi=0.;
	/*stmts*/
	_partial_der__der_building_livingZone_calc_Phi_Phi__der_building_livingZone_calc_Phi_Q=0;
	_partial_der__der_building_livingZone_calc_Phi_Phi__der_building_livingZone_calc_Phi_P=0;
	if (__der_building_livingZone_calc_Phi_P_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		_partial_der__der_building_livingZone_calc_Phi_P_act__der_building_livingZone_calc_Phi_P=((P>1e-10||P<-1e-10) ? (1) : (0));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_livingZone_calc_Phi_Phi__der_building_livingZone_calc_Phi_P=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (-((Q*_partial_der__der_building_livingZone_calc_Phi_P_act__der_building_livingZone_calc_Phi_P)/(P_act*P_act))*(((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))) : (0));
	}
	if (__der_building_livingZone_calc_Phi_Q_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_livingZone_calc_Phi_Phi__der_building_livingZone_calc_Phi_Q=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? ((((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))/P_act) : (0));
	}
	__der_building_livingZone_calc_Phi_Phi_dot=_partial_der__der_building_livingZone_calc_Phi_Phi__der_building_livingZone_calc_Phi_P*__der_building_livingZone_calc_Phi_P_dot+_partial_der__der_building_livingZone_calc_Phi_Phi__der_building_livingZone_calc_Phi_Q*__der_building_livingZone_calc_Phi_Q_dot;
	return __der_building_livingZone_calc_Phi_Phi_dot;
}

ITI_real _der_building_livingZone_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U, ITI_real __der_building_livingZone_calc_current_P_dot, ITI_real __der_building_livingZone_calc_current_Q_dot){
	ITI_real _partial_der__der_building_livingZone_calc_current_current__der_building_livingZone_calc_current_P=0.;
	ITI_real _partial_der__der_building_livingZone_calc_current_current__der_building_livingZone_calc_current_Q=0.;
	ITI_real __der_building_livingZone_calc_current_current_dot=0.;
	ITI_real S=0.;
	ITI_real current=0.;
	ITI_real _partial_der__der_building_livingZone_calc_current_S__der_building_livingZone_calc_current_P=0.;
	ITI_real _partial_der__der_building_livingZone_calc_current_S__der_building_livingZone_calc_current_Q=0.;
	/*stmts*/
	_partial_der__der_building_livingZone_calc_current_current__der_building_livingZone_calc_current_Q=0;
	_partial_der__der_building_livingZone_calc_current_current__der_building_livingZone_calc_current_P=0;
	if (__der_building_livingZone_calc_current_P_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_livingZone_calc_current_S__der_building_livingZone_calc_current_P=((P*P+Q*Q==0) ? (((2*P==0) ? (0) : (100000000.))) : (P/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_livingZone_calc_current_current__der_building_livingZone_calc_current_P=((fabs(U)>1e-10) ? (_partial_der__der_building_livingZone_calc_current_S__der_building_livingZone_calc_current_P/U) : (0));
	}
	if (__der_building_livingZone_calc_current_Q_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_livingZone_calc_current_S__der_building_livingZone_calc_current_Q=((P*P+Q*Q==0) ? (((2*Q==0) ? (0) : (100000000.))) : (Q/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_livingZone_calc_current_current__der_building_livingZone_calc_current_Q=((fabs(U)>1e-10) ? (_partial_der__der_building_livingZone_calc_current_S__der_building_livingZone_calc_current_Q/U) : (0));
	}
	__der_building_livingZone_calc_current_current_dot=_partial_der__der_building_livingZone_calc_current_current__der_building_livingZone_calc_current_P*__der_building_livingZone_calc_current_P_dot+_partial_der__der_building_livingZone_calc_current_current__der_building_livingZone_calc_current_Q*__der_building_livingZone_calc_current_Q_dot;
	return __der_building_livingZone_calc_current_current_dot;
}

ITI_real _building_livingZone_BaseLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_livingZone_ElectricalPower_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_livingZone_LightLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_livingZone_MachineLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_livingZone_NormLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_livingZone_NumberPerson_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_livingZone_ReactivePower_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_presenceTable_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _der_building_roof_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real __der_building_roof_calc_Phi_P_dot, ITI_real __der_building_roof_calc_Phi_Q_dot){
	ITI_real Phi=0.;
	ITI_real _partial_der__der_building_roof_calc_Phi_Phi__der_building_roof_calc_Phi_Q=0.;
	ITI_real _partial_der__der_building_roof_calc_Phi_Phi__der_building_roof_calc_Phi_P=0.;
	ITI_real _partial_der__der_building_roof_calc_Phi_P_act__der_building_roof_calc_Phi_P=0.;
	ITI_real P_act=0.;
	ITI_real __der_building_roof_calc_Phi_Phi_dot=0.;
	/*stmts*/
	_partial_der__der_building_roof_calc_Phi_Phi__der_building_roof_calc_Phi_Q=0;
	_partial_der__der_building_roof_calc_Phi_Phi__der_building_roof_calc_Phi_P=0;
	if (__der_building_roof_calc_Phi_P_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		_partial_der__der_building_roof_calc_Phi_P_act__der_building_roof_calc_Phi_P=((P>1e-10||P<-1e-10) ? (1) : (0));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_roof_calc_Phi_Phi__der_building_roof_calc_Phi_P=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (-((Q*_partial_der__der_building_roof_calc_Phi_P_act__der_building_roof_calc_Phi_P)/(P_act*P_act))*(((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))) : (0));
	}
	if (__der_building_roof_calc_Phi_Q_dot!=0){
		P_act=((P>1e-10||P<-1e-10) ? (P) : (1e-10*sign(P)));
		Phi=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? (((P_act>=0) ? (atan(Q/P_act)) : ((((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))+atan(Q/P_act)))) : (((fabs(Q)>1e-10) ? (0.5*(((Q>0) ? (3.1415926535897931) : (-3.1415926535897931)))) : (((P_act>=0) ? (0) : (-3.1415926535897931))))));
		_partial_der__der_building_roof_calc_Phi_Phi__der_building_roof_calc_Phi_Q=((fabs(P_act)>1e-10&&fabs(Q)>1e-10) ? ((((Q/P_act<100000.&&Q/P_act>-100000.) ? (1/(1+Q*Q/(P_act*P_act))) : (0)))/P_act) : (0));
	}
	__der_building_roof_calc_Phi_Phi_dot=_partial_der__der_building_roof_calc_Phi_Phi__der_building_roof_calc_Phi_P*__der_building_roof_calc_Phi_P_dot+_partial_der__der_building_roof_calc_Phi_Phi__der_building_roof_calc_Phi_Q*__der_building_roof_calc_Phi_Q_dot;
	return __der_building_roof_calc_Phi_Phi_dot;
}

ITI_real _der_building_roof_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U, ITI_real __der_building_roof_calc_current_P_dot, ITI_real __der_building_roof_calc_current_Q_dot){
	ITI_real _partial_der__der_building_roof_calc_current_current__der_building_roof_calc_current_Q=0.;
	ITI_real _partial_der__der_building_roof_calc_current_S__der_building_roof_calc_current_P=0.;
	ITI_real _partial_der__der_building_roof_calc_current_current__der_building_roof_calc_current_P=0.;
	ITI_real current=0.;
	ITI_real S=0.;
	ITI_real _partial_der__der_building_roof_calc_current_S__der_building_roof_calc_current_Q=0.;
	ITI_real __der_building_roof_calc_current_current_dot=0.;
	/*stmts*/
	_partial_der__der_building_roof_calc_current_current__der_building_roof_calc_current_Q=0;
	_partial_der__der_building_roof_calc_current_current__der_building_roof_calc_current_P=0;
	if (__der_building_roof_calc_current_P_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_roof_calc_current_S__der_building_roof_calc_current_P=((P*P+Q*Q==0) ? (((2*P==0) ? (0) : (100000000.))) : (P/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_roof_calc_current_current__der_building_roof_calc_current_P=((fabs(U)>1e-10) ? (_partial_der__der_building_roof_calc_current_S__der_building_roof_calc_current_P/U) : (0));
	}
	if (__der_building_roof_calc_current_Q_dot!=0){
		S=sqrt(P*P+Q*Q);
		_partial_der__der_building_roof_calc_current_S__der_building_roof_calc_current_Q=((P*P+Q*Q==0) ? (((2*Q==0) ? (0) : (100000000.))) : (Q/sqrt(P*P+Q*Q)));
		current=((fabs(U)>1e-10) ? (S/U) : (0));
		_partial_der__der_building_roof_calc_current_current__der_building_roof_calc_current_Q=((fabs(U)>1e-10) ? (_partial_der__der_building_roof_calc_current_S__der_building_roof_calc_current_Q/U) : (0));
	}
	__der_building_roof_calc_current_current_dot=_partial_der__der_building_roof_calc_current_current__der_building_roof_calc_current_P*__der_building_roof_calc_current_P_dot+_partial_der__der_building_roof_calc_current_current__der_building_roof_calc_current_Q*__der_building_roof_calc_current_Q_dot;
	return __der_building_roof_calc_current_current_dot;
}

ITI_real _building_roof_BaseLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_roof_ElectricalPower_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_roof_LightLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_roof_MachineLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_roof_NormLoad_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_roof_NumberPerson_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_roof_ReactivePower_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _environment_WeatherData_getDerTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable, ITI_real der_u){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getDerValue(tableID, icol, u, der_u);
}

ITI_real _building_cellar_groundDot(Param_Declare_SimVar, Param_Declare_SimData, ITI_real depthGround, ITI_real DayOfYear, ITI_int LeapYear, ITI_real cGround, ITI_real lambdaGround, ITI_real rhoGround, ITI_real GeoGradient, ITI_real TAmbientAverage, ITI_real TAmbientMax, ITI_int MaxMonth, ITI_real depthGroundDot, ITI_real DayOfYearDot, ITI_real cGroundDot, ITI_real lambdaGroundDot, ITI_real rhoGroundDot, ITI_real GeoGradientDot, ITI_real TAmbientAverageDot, ITI_real TAmbientMaxDot){
	ITI_real a=0.;
	ITI_real PhaseDisplacementDot=0.;
	ITI_real xiDot=0.;
	ITI_real PhaseDisplacement=0.;
	ITI_real TimePeriodDot=0.;
	ITI_real aDot=0.;
	ITI_real TimePeriod=0.;
	ITI_real xi=0.;
	ITI_real TGroundDot=0.;
	/*stmts*/
	a=lambdaGround/(rhoGround*cGround);
	PhaseDisplacement=2*3.1415926535897931*MaxMonth/12;
	aDot=0;
	xiDot=0;
	TimePeriodDot=0;
	PhaseDisplacementDot=0;
	if (LeapYear){
		TimePeriod=366*24*3600;
	}
	else {
		TimePeriod=365*24*3600;
	}
	xi=depthGround*sqrt(3.1415926535897931/(a*TimePeriod));
	TGroundDot=(TAmbientMax-TAmbientAverage)*ITI_exp(-xi)*-(2*3.1415926535897931*24*3600*DayOfYearDot/TimePeriod)*sin(2*3.1415926535897931*DayOfYear*24*3600/TimePeriod-PhaseDisplacement-xi);
	return TGroundDot;
}

ITI_real _der_environment_angleRadian(Param_Declare_SimVar, Param_Declare_SimData, ITI_real angleDeg, ITI_real __der_environment_angleRadian_angleDeg_dot){
	ITI_real _partial_der__der_environment_angleRadian_angleRad__der_environment_angleRadian_angleDeg=0.;
	ITI_real angleRad=0.;
	ITI_real __der_environment_angleRadian_angleRad_dot=0.;
	/*stmts*/
	_partial_der__der_environment_angleRadian_angleRad__der_environment_angleRadian_angleDeg=0;
	if (__der_environment_angleRadian_angleDeg_dot!=0){
		angleRad=0.017453292519943295*angleDeg;
		_partial_der__der_environment_angleRadian_angleRad__der_environment_angleRadian_angleDeg=0.017453292519943295;
	}
	__der_environment_angleRadian_angleRad_dot=_partial_der__der_environment_angleRadian_angleRad__der_environment_angleRadian_angleDeg*__der_environment_angleRadian_angleDeg_dot;
	return __der_environment_angleRadian_angleRad_dot;
}

void* _Modelica_Blocks_Types_ExternalCombiTable1D_constructor(Param_Declare_SimVar, Param_Declare_SimData, const ITI_char* tableName, const ITI_char* fileName, ITI_Array table, ITI_Array columns, ITI_int smoothness){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_init(tableName, fileName, table.realValues, __ARRAY_SIZE(table, 1), __ARRAY_SIZE(table, 2), columns.intValues, __ARRAY_SIZE(columns, 1), smoothness);
}

void _Modelica_Blocks_Types_ExternalCombiTable1D_destructor(Param_Declare_SimVar, Param_Declare_SimData, void* externalCombiTable1D){
	/*stmts*/
	ModelicaStandardTables_CombiTable1D_close(externalCombiTable1D);
}

ITI_int _Modelica_Utilities_Strings_length(Param_Declare_SimVar, Param_Declare_SimData, const ITI_char* string){
	/*stmts*/
	return ModelicaStrings_length(string);
}

ITI_int _Modelica_Utilities_Strings_Advanced_skipWhiteSpace(Param_Declare_SimVar, Param_Declare_SimData, const ITI_char* string, ITI_int startIndex){
	/*stmts*/
	return ModelicaStrings_skipWhiteSpace(string, startIndex);
}

ITI_int _Modelica_Utilities_Strings_isEmpty(Param_Declare_SimVar, Param_Declare_SimData, const ITI_char* string){
	ITI_int nextIndex=0;
	ITI_int len=0;
	ITI_int result=0;
	/*stmts*/
	nextIndex=_Modelica_Utilities_Strings_Advanced_skipWhiteSpace(Param_Passing_SimVar, Param_Passing_SimData, string,1);
	len=_Modelica_Utilities_Strings_length(Param_Passing_SimVar, Param_Passing_SimData, string);
	if (len<1||nextIndex>len){
		result=1;
	}
	else {
		result=0;
	}
	return result;
}

const ITI_char* _GreenCity_Utilities_Functions_getSimulationDataDirectory(Param_Declare_SimVar, Param_Declare_SimData){
	const ITI_char* out="";
	/*stmts*/
	__STRING_ASSIGN(out,"C:\\Users\\Public\\Documents\\SimulationX 4.2\\Modelica\\GreenCity\\Data\\SimulationData");
	return out;
}

ITI_Array _environment_normalVector2D(Param_Declare_SimVar, Param_Declare_SimData, ITI_real alpha){
	ITI_Array vector2D={0,0,0,0,0,REAL_TYPE};
	vector2D.nDims=1;
	vector2D.dims=GetIntMemory_F(1);
	vector2D.dims[0]=2;
	vector2D.memType=REAL_TYPE;
	vector2D.realValues=GetRealMemory_F(2);
	/*stmts*/
	vector2D.realValues[ArrayIndex(vector2D, "d", 1-1)]=cos(alpha);
	vector2D.realValues[ArrayIndex(vector2D, "d", 2-1)]=sin(alpha);
	return vector2D;
}

ITI_Array _environment_normalVector(Param_Declare_SimVar, Param_Declare_SimData, ITI_real alpha_inc, ITI_real alpha_or){
	ITI_Array vector={0,0,0,0,0,REAL_TYPE};
	vector.nDims=1;
	vector.dims=GetIntMemory_F(1);
	vector.dims[0]=3;
	vector.memType=REAL_TYPE;
	vector.realValues=GetRealMemory_F(3);
	/*stmts*/
	vector.realValues[ArrayIndex(vector, "d", 1-1)]=sin(alpha_inc)*cos(alpha_or);
	vector.realValues[ArrayIndex(vector, "d", 2-1)]=sin(alpha_inc)*sin(alpha_or);
	vector.realValues[ArrayIndex(vector, "d", 3-1)]=cos(alpha_inc);
	return vector;
}

ITI_real _environment_getAzimuth(Param_Declare_SimVar, Param_Declare_SimData, ITI_real actRealHour, ITI_real SolAlt, ITI_real lat, ITI_real delta){
	ITI_int sign=0;
	ITI_real azimuth=0.;
	/*stmts*/
	if (actRealHour<=12){
		sign=-1;
	}
	else {
		sign=1;
	}
	azimuth=3.1415926535897931+sign*acos(__iti_real_min(__iti_real_max((sin(SolAlt)*sin(lat)-sin(delta))/(cos(SolAlt)*cos(lat)), -1), 1));
	return azimuth;
}

ITI_real _environment_getVectorValue(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_real indexReal){
	ITI_real value=0.;
	ITI_int index=0;
	ITI_int last=0;
	ITI_int first=0;
	/*stmts*/
	first=1;
	last=12;
	index=(int)(__iti_real_min(__iti_int_max((int)floor(floor(indexReal)), first), last));
	value=u.intValues[ArrayIndex(u, "d", index-1)];
	return value;
}

ITI_real _environment_WeatherData_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _environment_Init_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_sumVector2(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_Array v, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_sumVector2__for__i;
		for (building_sumVector2__for__i=first;__LOOP_LIMIT_NOTREACHED(building_sumVector2__for__i,last,1); building_sumVector2__for__i=building_sumVector2__for__i+1){
			if (v.realValues[ArrayIndex(v, "d", building_sumVector2__for__i-1)]<=0.001){
				y=y+u.realValues[ArrayIndex(u, "d", building_sumVector2__for__i-1)];
			}
			else {
				y=y+0;
			}
		}
	}
	return y;
}

ITI_real _building_sumVector1(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_Array v, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_sumVector1__for__i;
		for (building_sumVector1__for__i=first;__LOOP_LIMIT_NOTREACHED(building_sumVector1__for__i,last,1); building_sumVector1__for__i=building_sumVector1__for__i+1){
			if (v.realValues[ArrayIndex(v, "d", building_sumVector1__for__i-1)]>0.001){
				y=y+u.realValues[ArrayIndex(u, "d", building_sumVector1__for__i-1)];
			}
			else {
				y=y+0;
			}
		}
	}
	return y;
}

ITI_real _building_sumVector(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_sumVector__for__i;
		for (building_sumVector__for__i=first;__LOOP_LIMIT_NOTREACHED(building_sumVector__for__i,last,1); building_sumVector__for__i=building_sumVector__for__i+1){
			y=y+u.realValues[ArrayIndex(u, "d", building_sumVector__for__i-1)];
		}
	}
	return y;
}

ITI_real _building_roof_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U){
	ITI_real S=0.;
	ITI_real current=0.;
	/*stmts*/
	S=sqrt(P*P+Q*Q);
	if (fabs(U)>1e-10){
		current=S/U;
	}
	else {
		current=0;
	}
	return current;
}

ITI_real _building_roof_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q){
	ITI_real P_act=0.;
	ITI_real Phi=0.;
	/*stmts*/
	if (P>1e-10){
		P_act=P;
	}
	else if (P<-1e-10){
		P_act=P;
	}
	else {
		P_act=1e-10*sign(P);
	}
	if (fabs(P_act)>1e-10&&fabs(Q)>1e-10){
		if (P_act>=0){
			Phi=atan(Q/P_act);
		}
		else {
			if (Q>0){
				Phi=3.1415926535897931+atan(Q/P_act);
			}
			else {
				Phi=-3.1415926535897931+atan(Q/P_act);
			}
		}
	}
	else {
		if (fabs(Q)>1e-10){
			if (Q>0){
				Phi=3.1415926535897931/2;
			}
			else {
				Phi=-3.1415926535897931/2;
			}
		}
		else {
			if (P_act>=0){
				Phi=0;
			}
			else {
				Phi=-3.1415926535897931;
			}
		}
	}
	return Phi;
}

ITI_real _building_roof_sumVector(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_roof_sumVector__for__i;
		for (building_roof_sumVector__for__i=first;__LOOP_LIMIT_NOTREACHED(building_roof_sumVector__for__i,last,1); building_roof_sumVector__for__i=building_roof_sumVector__for__i+1){
			y=y+u.realValues[ArrayIndex(u, "d", building_roof_sumVector__for__i-1)];
		}
	}
	return y;
}

ITI_real _building_roof_sumVector2(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_Array v, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_roof_sumVector2__for__i;
		for (building_roof_sumVector2__for__i=first;__LOOP_LIMIT_NOTREACHED(building_roof_sumVector2__for__i,last,1); building_roof_sumVector2__for__i=building_roof_sumVector2__for__i+1){
			if (v.realValues[ArrayIndex(v, "d", building_roof_sumVector2__for__i-1)]<=0.001){
				y=y+u.realValues[ArrayIndex(u, "d", building_roof_sumVector2__for__i-1)];
			}
			else {
				y=y+0;
			}
		}
	}
	return y;
}

ITI_real _building_roof_sumVector1(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_Array v, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_roof_sumVector1__for__i;
		for (building_roof_sumVector1__for__i=first;__LOOP_LIMIT_NOTREACHED(building_roof_sumVector1__for__i,last,1); building_roof_sumVector1__for__i=building_roof_sumVector1__for__i+1){
			if (v.realValues[ArrayIndex(v, "d", building_roof_sumVector1__for__i-1)]>0.001){
				y=y+u.realValues[ArrayIndex(u, "d", building_roof_sumVector1__for__i-1)];
			}
			else {
				y=y+0;
			}
		}
	}
	return y;
}

ITI_real _building_roof_diffAngle(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array vector1, ITI_Array vector2){
	ITI_real value=0.;
	ITI_real minMax=0.;
	ITI_real angle=0.;
	/*stmts*/
	value=(vector1.realValues[ArrayIndex(vector1, "d", 1-1)]*vector2.realValues[ArrayIndex(vector2, "d", 1-1)]+vector1.realValues[ArrayIndex(vector1, "d", 2-1)]*vector2.realValues[ArrayIndex(vector2, "d", 2-1)]+vector1.realValues[ArrayIndex(vector1, "d", 3-1)]*vector2.realValues[ArrayIndex(vector2, "d", 3-1)])/(sqrt(vector1.realValues[ArrayIndex(vector1, "d", 1-1)]*vector1.realValues[ArrayIndex(vector1, "d", 1-1)]+vector1.realValues[ArrayIndex(vector1, "d", 2-1)]*vector1.realValues[ArrayIndex(vector1, "d", 2-1)]+vector1.realValues[ArrayIndex(vector1, "d", 3-1)]*vector1.realValues[ArrayIndex(vector1, "d", 3-1)])*sqrt(vector2.realValues[ArrayIndex(vector2, "d", 1-1)]*vector2.realValues[ArrayIndex(vector2, "d", 1-1)]+vector2.realValues[ArrayIndex(vector2, "d", 2-1)]*vector2.realValues[ArrayIndex(vector2, "d", 2-1)]+vector2.realValues[ArrayIndex(vector2, "d", 3-1)]*vector2.realValues[ArrayIndex(vector2, "d", 3-1)]));
	minMax=__iti_real_max(__iti_real_min(value, 1), -1);
	angle=acos(minMax);
	return angle;
}

ITI_real _building_roof_ThreeVectorMult(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array vector1, ITI_Array vector2, ITI_Array vector3, ITI_int length){
	ITI_real prod=0.;
	/*stmts*/
	prod=0;
	{
		ITI_int building_roof_ThreeVectorMult__for__i;
		for (building_roof_ThreeVectorMult__for__i=1;__LOOP_LIMIT_NOTREACHED(building_roof_ThreeVectorMult__for__i,length,1); building_roof_ThreeVectorMult__for__i=building_roof_ThreeVectorMult__for__i+1){
			prod=prod+vector1.realValues[ArrayIndex(vector1, "d", building_roof_ThreeVectorMult__for__i-1)]*vector2.realValues[ArrayIndex(vector2, "d", building_roof_ThreeVectorMult__for__i-1)]*vector3.realValues[ArrayIndex(vector3, "d", building_roof_ThreeVectorMult__for__i-1)];
		}
	}
	return prod;
}

ITI_real _building_roof_ReactivePower_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_roof_NumberPerson_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_roof_NormLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_roof_MachineLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_roof_LightLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_roof_InnerLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_roof_ElectricalPower_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_roof_BaseLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_presenceTable_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_powerOutput1_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U){
	ITI_real current=0.;
	ITI_real S=0.;
	/*stmts*/
	S=sqrt(P*P+Q*Q);
	if (fabs(U)>1e-10){
		current=S/U;
	}
	else {
		current=0;
	}
	return current;
}

ITI_real _building_powerOutput1_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q){
	ITI_real P_act=0.;
	ITI_real Phi=0.;
	/*stmts*/
	if (P>1e-10){
		P_act=P;
	}
	else if (P<-1e-10){
		P_act=P;
	}
	else {
		P_act=1e-10*sign(P);
	}
	if (fabs(P_act)>1e-10&&fabs(Q)>1e-10){
		if (P_act>=0){
			Phi=atan(Q/P_act);
		}
		else {
			if (Q>0){
				Phi=3.1415926535897931+atan(Q/P_act);
			}
			else {
				Phi=-3.1415926535897931+atan(Q/P_act);
			}
		}
	}
	else {
		if (fabs(Q)>1e-10){
			if (Q>0){
				Phi=3.1415926535897931/2;
			}
			else {
				Phi=-3.1415926535897931/2;
			}
		}
		else {
			if (P_act>=0){
				Phi=0;
			}
			else {
				Phi=-3.1415926535897931;
			}
		}
	}
	return Phi;
}

ITI_real _building_livingZone_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U){
	ITI_real S=0.;
	ITI_real current=0.;
	/*stmts*/
	S=sqrt(P*P+Q*Q);
	if (fabs(U)>1e-10){
		current=S/U;
	}
	else {
		current=0;
	}
	return current;
}

ITI_real _building_livingZone_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q){
	ITI_real P_act=0.;
	ITI_real Phi=0.;
	/*stmts*/
	if (P>1e-10){
		P_act=P;
	}
	else if (P<-1e-10){
		P_act=P;
	}
	else {
		P_act=1e-10*sign(P);
	}
	if (fabs(P_act)>1e-10&&fabs(Q)>1e-10){
		if (P_act>=0){
			Phi=atan(Q/P_act);
		}
		else {
			if (Q>0){
				Phi=3.1415926535897931+atan(Q/P_act);
			}
			else {
				Phi=-3.1415926535897931+atan(Q/P_act);
			}
		}
	}
	else {
		if (fabs(Q)>1e-10){
			if (Q>0){
				Phi=3.1415926535897931/2;
			}
			else {
				Phi=-3.1415926535897931/2;
			}
		}
		else {
			if (P_act>=0){
				Phi=0;
			}
			else {
				Phi=-3.1415926535897931;
			}
		}
	}
	return Phi;
}

ITI_real _building_livingZone_sumVector(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_livingZone_sumVector__for__i;
		for (building_livingZone_sumVector__for__i=first;__LOOP_LIMIT_NOTREACHED(building_livingZone_sumVector__for__i,last,1); building_livingZone_sumVector__for__i=building_livingZone_sumVector__for__i+1){
			y=y+u.realValues[ArrayIndex(u, "d", building_livingZone_sumVector__for__i-1)];
		}
	}
	return y;
}

ITI_real _building_livingZone_sumVector2(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_Array v, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_livingZone_sumVector2__for__i;
		for (building_livingZone_sumVector2__for__i=first;__LOOP_LIMIT_NOTREACHED(building_livingZone_sumVector2__for__i,last,1); building_livingZone_sumVector2__for__i=building_livingZone_sumVector2__for__i+1){
			if (v.realValues[ArrayIndex(v, "d", building_livingZone_sumVector2__for__i-1)]<=0.001){
				y=y+u.realValues[ArrayIndex(u, "d", building_livingZone_sumVector2__for__i-1)];
			}
			else {
				y=y+0;
			}
		}
	}
	return y;
}

ITI_real _building_livingZone_sumVector1(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_Array v, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_livingZone_sumVector1__for__i;
		for (building_livingZone_sumVector1__for__i=first;__LOOP_LIMIT_NOTREACHED(building_livingZone_sumVector1__for__i,last,1); building_livingZone_sumVector1__for__i=building_livingZone_sumVector1__for__i+1){
			if (v.realValues[ArrayIndex(v, "d", building_livingZone_sumVector1__for__i-1)]>0.001){
				y=y+u.realValues[ArrayIndex(u, "d", building_livingZone_sumVector1__for__i-1)];
			}
			else {
				y=y+0;
			}
		}
	}
	return y;
}

ITI_real _building_livingZone_diffAngle(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array vector1, ITI_Array vector2){
	ITI_real value=0.;
	ITI_real minMax=0.;
	ITI_real angle=0.;
	/*stmts*/
	value=(vector1.realValues[ArrayIndex(vector1, "d", 1-1)]*vector2.realValues[ArrayIndex(vector2, "d", 1-1)]+vector1.realValues[ArrayIndex(vector1, "d", 2-1)]*vector2.realValues[ArrayIndex(vector2, "d", 2-1)]+vector1.realValues[ArrayIndex(vector1, "d", 3-1)]*vector2.realValues[ArrayIndex(vector2, "d", 3-1)])/(sqrt(vector1.realValues[ArrayIndex(vector1, "d", 1-1)]*vector1.realValues[ArrayIndex(vector1, "d", 1-1)]+vector1.realValues[ArrayIndex(vector1, "d", 2-1)]*vector1.realValues[ArrayIndex(vector1, "d", 2-1)]+vector1.realValues[ArrayIndex(vector1, "d", 3-1)]*vector1.realValues[ArrayIndex(vector1, "d", 3-1)])*sqrt(vector2.realValues[ArrayIndex(vector2, "d", 1-1)]*vector2.realValues[ArrayIndex(vector2, "d", 1-1)]+vector2.realValues[ArrayIndex(vector2, "d", 2-1)]*vector2.realValues[ArrayIndex(vector2, "d", 2-1)]+vector2.realValues[ArrayIndex(vector2, "d", 3-1)]*vector2.realValues[ArrayIndex(vector2, "d", 3-1)]));
	minMax=__iti_real_max(__iti_real_min(value, 1), -1);
	angle=acos(minMax);
	return angle;
}

ITI_real _building_livingZone_ThreeVectorMult(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array vector1, ITI_Array vector2, ITI_Array vector3, ITI_int length){
	ITI_real prod=0.;
	/*stmts*/
	prod=0;
	{
		ITI_int building_livingZone_ThreeVectorMult__for__i;
		for (building_livingZone_ThreeVectorMult__for__i=1;__LOOP_LIMIT_NOTREACHED(building_livingZone_ThreeVectorMult__for__i,length,1); building_livingZone_ThreeVectorMult__for__i=building_livingZone_ThreeVectorMult__for__i+1){
			prod=prod+vector1.realValues[ArrayIndex(vector1, "d", building_livingZone_ThreeVectorMult__for__i-1)]*vector2.realValues[ArrayIndex(vector2, "d", building_livingZone_ThreeVectorMult__for__i-1)]*vector3.realValues[ArrayIndex(vector3, "d", building_livingZone_ThreeVectorMult__for__i-1)];
		}
	}
	return prod;
}

ITI_real _building_livingZone_ReactivePower_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_livingZone_NumberPerson_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_livingZone_NormLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_livingZone_MachineLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_livingZone_LightLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_livingZone_InnerLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_livingZone_ElectricalPower_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_livingZone_BaseLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_grid_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U){
	ITI_real S=0.;
	ITI_real current=0.;
	/*stmts*/
	S=sqrt(P*P+Q*Q);
	if (fabs(U)>1e-10){
		current=S/U;
	}
	else {
		current=0;
	}
	return current;
}

ITI_real _building_grid_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q){
	ITI_real P_act=0.;
	ITI_real Phi=0.;
	/*stmts*/
	if (P>1e-10){
		P_act=P;
	}
	else if (P<-1e-10){
		P_act=P;
	}
	else {
		P_act=1e-10*sign(P);
	}
	if (fabs(P_act)>1e-10&&fabs(Q)>1e-10){
		if (P_act>=0){
			Phi=atan(Q/P_act);
		}
		else {
			if (Q>0){
				Phi=3.1415926535897931+atan(Q/P_act);
			}
			else {
				Phi=-3.1415926535897931+atan(Q/P_act);
			}
		}
	}
	else {
		if (fabs(Q)>1e-10){
			if (Q>0){
				Phi=3.1415926535897931/2;
			}
			else {
				Phi=-3.1415926535897931/2;
			}
		}
		else {
			if (P_act>=0){
				Phi=0;
			}
			else {
				Phi=-3.1415926535897931;
			}
		}
	}
	return Phi;
}

ITI_real _building_cellar_calc_current(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q, ITI_real U){
	ITI_real S=0.;
	ITI_real current=0.;
	/*stmts*/
	S=sqrt(P*P+Q*Q);
	if (fabs(U)>1e-10){
		current=S/U;
	}
	else {
		current=0;
	}
	return current;
}

ITI_real _building_cellar_calc_Phi(Param_Declare_SimVar, Param_Declare_SimData, ITI_real P, ITI_real Q){
	ITI_real P_act=0.;
	ITI_real Phi=0.;
	/*stmts*/
	if (P>1e-10){
		P_act=P;
	}
	else if (P<-1e-10){
		P_act=P;
	}
	else {
		P_act=1e-10*sign(P);
	}
	if (fabs(P_act)>1e-10&&fabs(Q)>1e-10){
		if (P_act>=0){
			Phi=atan(Q/P_act);
		}
		else {
			if (Q>0){
				Phi=3.1415926535897931+atan(Q/P_act);
			}
			else {
				Phi=-3.1415926535897931+atan(Q/P_act);
			}
		}
	}
	else {
		if (fabs(Q)>1e-10){
			if (Q>0){
				Phi=3.1415926535897931/2;
			}
			else {
				Phi=-3.1415926535897931/2;
			}
		}
		else {
			if (P_act>=0){
				Phi=0;
			}
			else {
				Phi=-3.1415926535897931;
			}
		}
	}
	return Phi;
}

ITI_real _building_cellar_sumVector(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_cellar_sumVector__for__i;
		for (building_cellar_sumVector__for__i=first;__LOOP_LIMIT_NOTREACHED(building_cellar_sumVector__for__i,last,1); building_cellar_sumVector__for__i=building_cellar_sumVector__for__i+1){
			y=y+u.realValues[ArrayIndex(u, "d", building_cellar_sumVector__for__i-1)];
		}
	}
	return y;
}

ITI_real _building_cellar_sumVector2(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_Array v, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_cellar_sumVector2__for__i;
		for (building_cellar_sumVector2__for__i=first;__LOOP_LIMIT_NOTREACHED(building_cellar_sumVector2__for__i,last,1); building_cellar_sumVector2__for__i=building_cellar_sumVector2__for__i+1){
			if (v.realValues[ArrayIndex(v, "d", building_cellar_sumVector2__for__i-1)]<=0.001){
				y=y+u.realValues[ArrayIndex(u, "d", building_cellar_sumVector2__for__i-1)];
			}
			else {
				y=y+0;
			}
		}
	}
	return y;
}

ITI_real _building_cellar_sumVector1(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_Array v, ITI_int first, ITI_int last){
	ITI_real y=0.;
	/*stmts*/
	y=0;
	{
		ITI_int building_cellar_sumVector1__for__i;
		for (building_cellar_sumVector1__for__i=first;__LOOP_LIMIT_NOTREACHED(building_cellar_sumVector1__for__i,last,1); building_cellar_sumVector1__for__i=building_cellar_sumVector1__for__i+1){
			if (v.realValues[ArrayIndex(v, "d", building_cellar_sumVector1__for__i-1)]>0.001){
				y=y+u.realValues[ArrayIndex(u, "d", building_cellar_sumVector1__for__i-1)];
			}
			else {
				y=y+0;
			}
		}
	}
	return y;
}

ITI_real _building_cellar_diffAngle(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array vector1, ITI_Array vector2){
	ITI_real value=0.;
	ITI_real minMax=0.;
	ITI_real angle=0.;
	/*stmts*/
	value=(vector1.realValues[ArrayIndex(vector1, "d", 1-1)]*vector2.realValues[ArrayIndex(vector2, "d", 1-1)]+vector1.realValues[ArrayIndex(vector1, "d", 2-1)]*vector2.realValues[ArrayIndex(vector2, "d", 2-1)]+vector1.realValues[ArrayIndex(vector1, "d", 3-1)]*vector2.realValues[ArrayIndex(vector2, "d", 3-1)])/(sqrt(vector1.realValues[ArrayIndex(vector1, "d", 1-1)]*vector1.realValues[ArrayIndex(vector1, "d", 1-1)]+vector1.realValues[ArrayIndex(vector1, "d", 2-1)]*vector1.realValues[ArrayIndex(vector1, "d", 2-1)]+vector1.realValues[ArrayIndex(vector1, "d", 3-1)]*vector1.realValues[ArrayIndex(vector1, "d", 3-1)])*sqrt(vector2.realValues[ArrayIndex(vector2, "d", 1-1)]*vector2.realValues[ArrayIndex(vector2, "d", 1-1)]+vector2.realValues[ArrayIndex(vector2, "d", 2-1)]*vector2.realValues[ArrayIndex(vector2, "d", 2-1)]+vector2.realValues[ArrayIndex(vector2, "d", 3-1)]*vector2.realValues[ArrayIndex(vector2, "d", 3-1)]));
	minMax=__iti_real_max(__iti_real_min(value, 1), -1);
	angle=acos(minMax);
	return angle;
}

ITI_real _building_cellar_ThreeVectorMult(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array vector1, ITI_Array vector2, ITI_Array vector3, ITI_int length){
	ITI_real prod=0.;
	/*stmts*/
	prod=0;
	{
		ITI_int building_cellar_ThreeVectorMult__for__i;
		for (building_cellar_ThreeVectorMult__for__i=1;__LOOP_LIMIT_NOTREACHED(building_cellar_ThreeVectorMult__for__i,length,1); building_cellar_ThreeVectorMult__for__i=building_cellar_ThreeVectorMult__for__i+1){
			prod=prod+vector1.realValues[ArrayIndex(vector1, "d", building_cellar_ThreeVectorMult__for__i-1)]*vector2.realValues[ArrayIndex(vector2, "d", building_cellar_ThreeVectorMult__for__i-1)]*vector3.realValues[ArrayIndex(vector3, "d", building_cellar_ThreeVectorMult__for__i-1)];
		}
	}
	return prod;
}

ITI_real _building_cellar_ground(Param_Declare_SimVar, Param_Declare_SimData, ITI_real depthGround, ITI_real DayOfYear, ITI_int LeapYear, ITI_real cGround, ITI_real lambdaGround, ITI_real rhoGround, ITI_real GeoGradient, ITI_real TAmbientAverage, ITI_real TAmbientMax, ITI_int MaxMonth){
	ITI_real a=0.;
	ITI_real PhaseDisplacement=0.;
	ITI_real TimePeriod=0.;
	ITI_real xi=0.;
	ITI_real TGround=0.;
	/*stmts*/
	a=lambdaGround/(rhoGround*cGround);
	PhaseDisplacement=2*3.1415926535897931*MaxMonth/12;
	if (LeapYear){
		TimePeriod=366*24*3600;
	}
	else {
		TimePeriod=365*24*3600;
	}
	xi=depthGround*sqrt(3.1415926535897931/(a*TimePeriod));
	TGround=TAmbientAverage+GeoGradient*depthGround+(TAmbientMax-TAmbientAverage)*ITI_exp(-xi)*cos(2*3.1415926535897931*DayOfYear*24*3600/TimePeriod-PhaseDisplacement-xi);
	return TGround;
}

ITI_real _building_cellar_ReactivePower_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_cellar_NumberPerson_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_cellar_NormLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_cellar_MachineLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_cellar_LightLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_cellar_InnerLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_cellar_ElectricalPower_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_cellar_BaseLoad_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_real _building_PelTable_getTableValue(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int icol, ITI_real u, ITI_real tableAvailable){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_getValue(tableID, icol, u);
}

ITI_int _environment_sumOfDays(Param_Declare_SimVar, Param_Declare_SimData, ITI_Array u, ITI_int first, ITI_int last){
	ITI_int sum=0;
	/*stmts*/
	sum=0;
	{
		ITI_int environment_sumOfDays__for__i;
		for (environment_sumOfDays__for__i=first;__LOOP_LIMIT_NOTREACHED(environment_sumOfDays__for__i,last,1); environment_sumOfDays__for__i=environment_sumOfDays__for__i+1){
			sum=sum+u.intValues[ArrayIndex(u, "d", environment_sumOfDays__for__i-1)];
		}
	}
	return sum;
}

void _environment_initTimeBaseUnix(Param_Declare_SimVar, Param_Declare_SimData, ITI_real tStart, ITI_real* HourOfDay, ITI_real* DayOfWeek, ITI_real* DayOfMonth, ITI_real* MonthOfYear, ITI_real* DayOfYear, ITI_real* Year, ITI_int* DSTEnableDay, ITI_int* DSTDisableDay){
	ITI_Array DaysLeap={0,0,0,0,0,REAL_TYPE};
	ITI_int auxYear=0;
	ITI_int InitDayOfWeek1969=0;
	ITI_Array DaysNoLeap={0,0,0,0,0,REAL_TYPE};
	ITI_int thisLeapYear=0;
	ITI_int auxMonth=0;
	ITI_int auxDayOfWeek1stJAN=0;
	ITI_int leapYearCount=0;
	ITI_int DayCounter=0;
	ITI_int thisYear=0;
	ITI_int auxDSTDayOfWeek=0;
	ITI_int LastSuOnMarch=0;
	ITI_int LastSuOnOctober=0;
	ITI_int auxDayOfWeek=0;
	ITI_Array cstrArray_213ebed8={0,0,0,0,0,REAL_TYPE};
	ITI_Array cstrArray_213ebf60={0,0,0,0,0,REAL_TYPE};
	/*stmts*/
	DaysLeap=(cstrArray_213ebed8.nDims=1,cstrArray_213ebed8.dims=GetIntMemory_M(1),cstrArray_213ebed8.dims[0]=12,cstrArray_213ebed8.memType=INT_TYPE,cstrArray_213ebed8.intValues=GetIntMemory_M(12),cstrArray_213ebed8.intValues[0]=31,cstrArray_213ebed8.intValues[1]=29,cstrArray_213ebed8.intValues[2]=31,cstrArray_213ebed8.intValues[3]=30,cstrArray_213ebed8.intValues[4]=31,cstrArray_213ebed8.intValues[5]=30,cstrArray_213ebed8.intValues[6]=31,cstrArray_213ebed8.intValues[7]=31,cstrArray_213ebed8.intValues[8]=30,cstrArray_213ebed8.intValues[9]=31,cstrArray_213ebed8.intValues[10]=30,cstrArray_213ebed8.intValues[11]=31,cstrArray_213ebed8);
	DaysNoLeap=(cstrArray_213ebf60.nDims=1,cstrArray_213ebf60.dims=GetIntMemory_M(1),cstrArray_213ebf60.dims[0]=12,cstrArray_213ebf60.memType=INT_TYPE,cstrArray_213ebf60.intValues=GetIntMemory_M(12),cstrArray_213ebf60.intValues[0]=31,cstrArray_213ebf60.intValues[1]=28,cstrArray_213ebf60.intValues[2]=31,cstrArray_213ebf60.intValues[3]=30,cstrArray_213ebf60.intValues[4]=31,cstrArray_213ebf60.intValues[5]=30,cstrArray_213ebf60.intValues[6]=31,cstrArray_213ebf60.intValues[7]=31,cstrArray_213ebf60.intValues[8]=30,cstrArray_213ebf60.intValues[9]=31,cstrArray_213ebf60.intValues[10]=30,cstrArray_213ebf60.intValues[11]=31,cstrArray_213ebf60);
	InitDayOfWeek1969=3;
	auxYear=(int)((int)floor(floor((tStart+3600)/(3600*24*365))));
	leapYearCount=0;
	{
		ITI_int environment_initTimeBaseUnix__for__i;
		for (environment_initTimeBaseUnix__for__i=1970;__LOOP_LIMIT_NOTREACHED(environment_initTimeBaseUnix__for__i,1970+auxYear,1); environment_initTimeBaseUnix__for__i=environment_initTimeBaseUnix__for__i+1){
			if ((floor(environment_initTimeBaseUnix__for__i)-(floor(floor(environment_initTimeBaseUnix__for__i)*1.0/4)*4))<=0||(floor(environment_initTimeBaseUnix__for__i)-(floor(floor(environment_initTimeBaseUnix__for__i)*1.0/400)*400))<=0){
				leapYearCount=leapYearCount+1;
			}
		}
	}
	if ((tStart+3600)-(auxYear*3600*24*365+(leapYearCount-1)*3600*24)>=0){
		thisYear=auxYear+1970;
	}
	else {
		thisYear=(auxYear+1970)-1;
	}
	auxDayOfWeek1stJAN=InitDayOfWeek1969;
	{
		ITI_int environment_initTimeBaseUnix__for_1_i;
		for (environment_initTimeBaseUnix__for_1_i=1970;__LOOP_LIMIT_NOTREACHED(environment_initTimeBaseUnix__for_1_i,thisYear,1); environment_initTimeBaseUnix__for_1_i=environment_initTimeBaseUnix__for_1_i+1){
			if ((floor(environment_initTimeBaseUnix__for_1_i)-(floor(floor(environment_initTimeBaseUnix__for_1_i)*1.0/4)*4))<=0||(floor(environment_initTimeBaseUnix__for_1_i)-(floor(floor(environment_initTimeBaseUnix__for_1_i)*1.0/400)*400))<=0){
				auxDayOfWeek1stJAN=auxDayOfWeek1stJAN+2;
			}
			else {
				auxDayOfWeek1stJAN=auxDayOfWeek1stJAN+1;
			}
			if (auxDayOfWeek1stJAN>8){
				auxDayOfWeek1stJAN=2;
			}
			else if (auxDayOfWeek1stJAN>7){
				auxDayOfWeek1stJAN=1;
			}
			else {
				auxDayOfWeek1stJAN=auxDayOfWeek1stJAN;
			}
		}
	}
	if ((floor(thisYear)-(floor(floor(thisYear)*1.0/4)*4))<=0||(floor(thisYear)-(floor(floor(thisYear)*1.0/400)*400))<=0){
		thisLeapYear=1;
	}
	else {
		thisLeapYear=0;
	}
	if (thisLeapYear){
		if (auxDayOfWeek1stJAN>1){
			auxDayOfWeek1stJAN=auxDayOfWeek1stJAN-1;
		}
		else {
			auxDayOfWeek1stJAN=7;
		}
	}
	else {
		auxDayOfWeek1stJAN=auxDayOfWeek1stJAN;
	}
	if (thisLeapYear){
		(*DayOfYear)=((tStart+3600)-(thisYear-1970)*3600*24*365-(leapYearCount-1)*3600*24)/(24*3600);
		auxDSTDayOfWeek=auxDayOfWeek1stJAN;
		LastSuOnMarch=0;
		LastSuOnOctober=0;
		DayCounter=1;
		{
			ITI_int environment_initTimeBaseUnix__for_2_i;
			for (environment_initTimeBaseUnix__for_2_i=1;__LOOP_LIMIT_NOTREACHED(environment_initTimeBaseUnix__for_2_i,365,1); environment_initTimeBaseUnix__for_2_i=environment_initTimeBaseUnix__for_2_i+1){
				auxDSTDayOfWeek=auxDSTDayOfWeek+1;
				DayCounter=DayCounter+1;
				if (auxDSTDayOfWeek>7){
					auxDSTDayOfWeek=1;
				}
				if (auxDSTDayOfWeek==7&&DayCounter<_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysLeap,1,3)){
					LastSuOnMarch=DayCounter;
				}
				if (auxDSTDayOfWeek==7&&DayCounter<_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysLeap,1,10)){
					LastSuOnOctober=DayCounter;
				}
			}
		}
		if ((*DayOfYear)>=335){
			auxMonth=12;
		}
		else if ((*DayOfYear)>=305){
			auxMonth=11;
		}
		else if ((*DayOfYear)>=274-((ITI_real)1)/24){
			auxMonth=10;
		}
		else if ((*DayOfYear)>=244-((ITI_real)1)/24){
			auxMonth=9;
		}
		else if ((*DayOfYear)>=213-((ITI_real)1)/24){
			auxMonth=8;
		}
		else if ((*DayOfYear)>=182-((ITI_real)1)/24){
			auxMonth=7;
		}
		else if ((*DayOfYear)>=152-((ITI_real)1)/24){
			auxMonth=6;
		}
		else if ((*DayOfYear)>=121-((ITI_real)1)/24){
			auxMonth=5;
		}
		else if ((*DayOfYear)>=91-((ITI_real)1)/24){
			auxMonth=4;
		}
		else if ((*DayOfYear)>=60){
			auxMonth=3;
		}
		else if ((*DayOfYear)>=31){
			auxMonth=2;
		}
		else {
			auxMonth=1;
		}
		if (auxMonth>1){
			if ((*DayOfYear)>LastSuOnMarch+((ITI_real)2)/24&&(*DayOfYear)<LastSuOnOctober+((ITI_real)3)/24){
				(*MonthOfYear)=auxMonth+((*DayOfYear)-_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysLeap,1,auxMonth-1))/DaysLeap.intValues[ArrayIndex(DaysLeap, "d", auxMonth-1)]+((ITI_real)1)/(24*DaysLeap.intValues[ArrayIndex(DaysLeap, "d", auxMonth-1)]);
				(*DayOfMonth)=((*DayOfYear)+((ITI_real)1)/24)-_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysLeap,1,auxMonth-1)+1;
			}
			else {
				(*MonthOfYear)=auxMonth+((*DayOfYear)-_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysLeap,1,auxMonth-1))/DaysLeap.intValues[ArrayIndex(DaysLeap, "d", auxMonth-1)];
				(*DayOfMonth)=(*DayOfYear)-_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysLeap,1,auxMonth-1)+1;
			}
		}
		else {
			if ((*DayOfYear)>LastSuOnMarch+((ITI_real)2)/24&&(*DayOfYear)<LastSuOnOctober+((ITI_real)3)/24){
				(*MonthOfYear)=auxMonth+(*DayOfYear)/DaysLeap.intValues[ArrayIndex(DaysLeap, "d", auxMonth-1)]+((ITI_real)1)/(24*DaysLeap.intValues[ArrayIndex(DaysLeap, "d", auxMonth-1)]);
				(*DayOfMonth)=(*DayOfYear)+((ITI_real)1)/24+1;
			}
			else {
				(*MonthOfYear)=auxMonth+(*DayOfYear)/DaysLeap.intValues[ArrayIndex(DaysLeap, "d", auxMonth-1)];
				(*DayOfMonth)=(*DayOfYear)+1;
			}
		}
		(*Year)=thisYear+(*DayOfYear)/_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysLeap,1,12);
	}
	else {
		(*DayOfYear)=((tStart+3600)-(thisYear-1970)*3600*24*365-leapYearCount*3600*24)/(24*3600);
		auxDSTDayOfWeek=auxDayOfWeek1stJAN;
		auxDayOfWeek=auxDayOfWeek1stJAN;
		LastSuOnMarch=0;
		LastSuOnOctober=0;
		DayCounter=1;
		{
			ITI_int environment_initTimeBaseUnix__for_3_i;
			for (environment_initTimeBaseUnix__for_3_i=1;__LOOP_LIMIT_NOTREACHED(environment_initTimeBaseUnix__for_3_i,364,1); environment_initTimeBaseUnix__for_3_i=environment_initTimeBaseUnix__for_3_i+1){
				auxDSTDayOfWeek=auxDSTDayOfWeek+1;
				DayCounter=DayCounter+1;
				if (auxDSTDayOfWeek>7){
					auxDSTDayOfWeek=1;
				}
				if (auxDSTDayOfWeek==7&&DayCounter<_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysNoLeap,1,3)){
					LastSuOnMarch=DayCounter;
				}
				if (auxDSTDayOfWeek==7&&DayCounter<_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysNoLeap,1,10)){
					LastSuOnOctober=DayCounter;
				}
			}
		}
		if ((*DayOfYear)>=334){
			auxMonth=12;
		}
		else if ((*DayOfYear)>=304){
			auxMonth=11;
		}
		else if ((*DayOfYear)>=273-((ITI_real)1)/24){
			auxMonth=10;
		}
		else if ((*DayOfYear)>=243-((ITI_real)1)/24){
			auxMonth=9;
		}
		else if ((*DayOfYear)>=212-((ITI_real)1)/24){
			auxMonth=8;
		}
		else if ((*DayOfYear)>=181-((ITI_real)1)/24){
			auxMonth=7;
		}
		else if ((*DayOfYear)>=151-((ITI_real)1)/24){
			auxMonth=6;
		}
		else if ((*DayOfYear)>=120-((ITI_real)1)/24){
			auxMonth=5;
		}
		else if ((*DayOfYear)>=90-((ITI_real)1)/24){
			auxMonth=4;
		}
		else if ((*DayOfYear)>=59){
			auxMonth=3;
		}
		else if ((*DayOfYear)>=31){
			auxMonth=2;
		}
		else {
			auxMonth=1;
		}
		if (auxMonth>1){
			if ((*DayOfYear)>LastSuOnMarch+((ITI_real)2)/24&&(*DayOfYear)<LastSuOnOctober+((ITI_real)3)/24){
				(*MonthOfYear)=auxMonth+((*DayOfYear)-_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysNoLeap,1,auxMonth-1))/DaysNoLeap.intValues[ArrayIndex(DaysNoLeap, "d", auxMonth-1)]+((ITI_real)1)/(24*DaysNoLeap.intValues[ArrayIndex(DaysNoLeap, "d", auxMonth-1)]);
				(*DayOfMonth)=((*DayOfYear)+((ITI_real)1)/24)-_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysNoLeap,1,auxMonth-1)+1;
			}
			else {
				(*MonthOfYear)=auxMonth+((*DayOfYear)-_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysNoLeap,1,auxMonth-1))/DaysNoLeap.intValues[ArrayIndex(DaysNoLeap, "d", auxMonth-1)];
				(*DayOfMonth)=(*DayOfYear)-_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysNoLeap,1,auxMonth-1)+1;
			}
		}
		else {
			if ((*DayOfYear)>LastSuOnMarch+((ITI_real)2)/24&&(*DayOfYear)<LastSuOnOctober+((ITI_real)3)/24){
				(*MonthOfYear)=auxMonth+(*DayOfYear)/DaysNoLeap.intValues[ArrayIndex(DaysNoLeap, "d", auxMonth-1)]+((ITI_real)1)/(24*DaysNoLeap.intValues[ArrayIndex(DaysNoLeap, "d", auxMonth-1)]);
				(*DayOfMonth)=(*DayOfYear)+((ITI_real)1)/24+1;
			}
			else {
				(*MonthOfYear)=auxMonth+(*DayOfYear)/DaysNoLeap.intValues[ArrayIndex(DaysNoLeap, "d", auxMonth-1)];
				(*DayOfMonth)=(*DayOfYear)+1;
			}
		}
		(*Year)=thisYear+(*DayOfYear)/_environment_sumOfDays(Param_Passing_SimVar, Param_Passing_SimData, DaysNoLeap,1,12);
	}
	(*HourOfDay)=((*DayOfMonth)-(int)floor(floor((*DayOfMonth))))*24;
	auxDayOfWeek=auxDayOfWeek1stJAN;
	{
		ITI_int environment_initTimeBaseUnix__for_4_i;
		for (environment_initTimeBaseUnix__for_4_i=1;__LOOP_LIMIT_NOTREACHED(environment_initTimeBaseUnix__for_4_i,(int)floor((*DayOfYear)),1); environment_initTimeBaseUnix__for_4_i=environment_initTimeBaseUnix__for_4_i+1){
			auxDayOfWeek=auxDayOfWeek+1;
			if (auxDayOfWeek>7){
				auxDayOfWeek=1;
			}
		}
	}
	if ((*DayOfYear)>=LastSuOnMarch&&(*DayOfYear)<LastSuOnOctober&&(*DayOfYear)-(int)floor(floor((*DayOfYear)))>((ITI_real)23)/24){
		if (auxDayOfWeek==7){
			auxDayOfWeek=1;
		}
		else {
			auxDayOfWeek=auxDayOfWeek+1;
		}
	}
	(*DSTEnableDay)=LastSuOnMarch;
	(*DSTDisableDay)=LastSuOnOctober;
	(*DayOfWeek)=auxDayOfWeek;
}

ITI_real _environment_WeatherData_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _environment_Init_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_roof_ReactivePower_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_roof_NumberPerson_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_roof_NormLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_roof_MachineLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_roof_LightLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_roof_InnerLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_roof_ElectricalPower_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_roof_BaseLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_presenceTable_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_livingZone_ReactivePower_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_livingZone_NumberPerson_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_livingZone_NormLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_livingZone_MachineLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_livingZone_LightLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_livingZone_InnerLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_livingZone_ElectricalPower_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_livingZone_BaseLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_cellar_ReactivePower_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_cellar_NumberPerson_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_cellar_NormLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_cellar_MachineLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_cellar_LightLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_cellar_InnerLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_cellar_ElectricalPower_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_cellar_BaseLoad_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

ITI_real _building_PelTable_readTableData(Param_Declare_SimVar, Param_Declare_SimData, void* tableID, ITI_int forceRead, ITI_int verboseRead){
	/*stmts*/
	return ModelicaStandardTables_CombiTable1D_read(tableID, forceRead, verboseRead);
}

void _AssignRec_GreenCity_Utilities_BuildingData_ParameterSelectionSCB_AgeOfBuilding_To1968(Param_Declare_SimVar, Param_Declare_SimData,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_AgeOfBuilding_To1968* _lhs,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_AgeOfBuilding_To1968 _rhs){
	_lhs->iBA=_rhs.iBA;
	_lhs->endOfBA=_rhs.endOfBA;
}
void _AssignRec_GreenCity_Utilities_BuildingData_ParameterSelectionSCB_BuildingType_Residential(Param_Declare_SimVar, Param_Declare_SimData,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_BuildingType_Residential* _lhs,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_BuildingType_Residential _rhs){
	_lhs->iBuild=_rhs.iBuild;
}
void _AssignRec_GreenCity_Utilities_BuildingData_ParameterSelectionSCB_WallType_Massive(Param_Declare_SimVar, Param_Declare_SimData,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_WallType_Massive* _lhs,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_WallType_Massive _rhs){
	_lhs->iType=_rhs.iType;
}
void _AssignRec_GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Basement_Unheated(Param_Declare_SimVar, Param_Declare_SimData,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Basement_Unheated* _lhs,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Basement_Unheated _rhs){
	_lhs->iCellar=_rhs.iCellar;
}
void _AssignRec_GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Roof_Unheated(Param_Declare_SimVar, Param_Declare_SimData,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Roof_Unheated* _lhs,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Roof_Unheated _rhs){
	_lhs->iRoof=_rhs.iRoof;
}
void _AssignRec_GreenCity_Utilities_BuildingData_ParameterSelectionSCB_AgeOfWindows_EnEV2016(Param_Declare_SimVar, Param_Declare_SimData,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_AgeOfWindows_EnEV2016* _lhs,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_AgeOfWindows_EnEV2016 _rhs){
	_lhs->iBA=_rhs.iBA;
	_lhs->endOfBA=_rhs.endOfBA;
}
void _AssignRec_GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Windows_Plastic(Param_Declare_SimVar, Param_Declare_SimData,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Windows_Plastic* _lhs,GreenCity_Utilities_BuildingData_ParameterSelectionSCB_Windows_Plastic _rhs){
	_lhs->iWindow=_rhs.iWindow;
}
